server:
    port: 10086
spring:
    profiles:
        active: dev
    application:
        name: gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true

