feign:
    httpclient:
        enabled: true
    sentinel:
        enabled: true
logging:
    level:
        com:
            orderservice:
                dao: debug
        org:
            springframework:
                web: debug
mybatis-plus:
    global-config:
        banner: false
    mapper-locations: classpath:mappers/*xml
    type-aliases-package: 'null'
server:
    port: 9090
spring:
    application:
        name: order-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        name: defaultDataSource
        password: root
        url: jdbc:mysql://localhost:3306/woniu-shopping?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
    jackson:
        time-zone: GMT+8
    main:
        banner-mode: false
