server:
  port: 9090
spring:
  main:
    banner-mode: off
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/department_service_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
mybatis-plus:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: 
  global-config:
    banner: off
